/*
 * Copyright (c) 2019 ChainFront LLC.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package pcrypto.cf.ethereum.api.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.Valid;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;


/**
 * Contract
 */
@ApiModel
public class EthereumContract
{

    @ApiModelProperty( value = "Solidity ABI of this contract. Generated by 'solcjs --abi my_contract.sol.'",
                       required = true,
                       position = 10 )
    private String solidityAbi = null;

    @ApiModelProperty( value = "Solidity bytecode of this contract. Generated by 'solcjs --bin my_contract.sol'.",
                       required = true,
                       position = 20 )
    private String solidityBytecode = null;

    @ApiModelProperty( value = "If required by the contract constructor, pass parameters to the constructor using this array.",
                       position = 30 )
    @Valid
    private List<String> params = new ArrayList<>();


    @ApiModelProperty( value = "If needed by this contract, the amount of wei to fund the contract account.",
                       position = 40 )
    @Valid
    private BigDecimal value = null;

    @ApiModelProperty( value = "The gas limit in wei for the transaction.",
                       position = 100 )
    @Valid
    private BigDecimal gasLimit = null;

    @ApiModelProperty( value = "Date the account was created.",
                       position = 1000,
                       accessMode = ApiModelProperty.AccessMode.READ_ONLY,
                       readOnly = true )
    @JsonProperty( "createdDate" )
    private OffsetDateTime createdDate = null;


    public String getSolidityAbi()
    {
        return solidityAbi;
    }

    public void setSolidityAbi( final String solidityAbi )
    {
        this.solidityAbi = solidityAbi;
    }

    public String getSolidityBytecode()
    {
        return solidityBytecode;
    }

    public void setSolidityBytecode( final String solidityBytecode )
    {
        this.solidityBytecode = solidityBytecode;
    }

    public List<String> getParams()
    {
        return params;
    }

    public void setParams( final List<String> params )
    {
        this.params = params;
    }

    public BigDecimal getValue()
    {
        return value;
    }

    public void setValue( final BigDecimal value )
    {
        this.value = value;
    }

    public BigDecimal getGasLimit()
    {
        return gasLimit;
    }

    public void setGasLimit( final BigDecimal gasLimit )
    {
        this.gasLimit = gasLimit;
    }

    public OffsetDateTime getCreatedDate()
    {
        return createdDate;
    }

    public void setCreatedDate( final OffsetDateTime createdDate )
    {
        this.createdDate = createdDate;
    }
}

