swagger: "2.0"

info:
  version: 0.9.0-alpha
  title: ChainFront Key Management Service - Ethereum

tags:
- name: Account Service
  description: Account management APIs
- name: Contract Service
  description: Contract APIs
- name: Payment Service
  description: Payment APIs

schemes:
- https

host: api.chainfront.io
basePath: /v1/eth

securityDefinitions:
  OAuth2:
    type: oauth2
    flow: accessCode
    authorizationUrl: 'https://api.chainfront.io/oauth/authorization'
    tokenUrl: 'https://api.chainfront.io/oauth/token'
    scopes:
      'admin': Admin scope
      'write:accounts': Ability to create accounts
      'read:accounts': Ability to read accounts
      'write:payments': Ability to create payment transactions
      'write:contracts': Ability to create contracts
      'read:contracts': Ability to read contracts
      'execute:contracts': Ability to execute contracts

security:
- OAuth2:
  - 'read:accounts'

paths:
  /accounts:
    get:
      tags:
      - Account Service
      summary: List accounts
      description: Returns a paginated list of all accounts.
      security:
      - OAuth2:
        - 'read:accounts'
      x-amazon-apigateway-integration:
        passthroughBehavior: "when_no_match"
        requestTemplates:
          application/json: "{\"statusCode\": 200}"
        type: "mock"
    post:
      tags:
      - Account Service
      summary: Create account
      description: Create a new account
      security:
      - OAuth2:
        - 'read:accounts'
        - 'write:accounts'
      x-amazon-apigateway-integration:
        passthroughBehavior: "when_no_match"
        requestTemplates:
          application/json: "{\"statusCode\": 200}"
        type: "mock"
  '/accounts/{name}':
    get:
      tags:
      - Account Service
      summary: Get account
      description: Returns account details for the given account name
      security:
      - OAuth2:
        - 'read:accounts'
      x-amazon-apigateway-integration:
        passthroughBehavior: "when_no_match"
        requestTemplates:
          application/json: "{\"statusCode\": 200}"
        type: "mock"
  /contracts:
    get:
      tags:
      - Contract Service
      summary: List contracts
      description: Returns a paginated list of all contracts.
      security:
      - OAuth2:
        - 'read:contracts'
      x-amazon-apigateway-integration:
        passthroughBehavior: "when_no_match"
        requestTemplates:
          application/json: "{\"statusCode\": 200}"
        type: "mock"
    post:
      tags:
      - Contract Service
      summary: Create contract
      description: Create a new contract
      security:
      - OAuth2:
        - 'read:contracts'
        - 'write:contracts'
      x-amazon-apigateway-integration:
        passthroughBehavior: "when_no_match"
        requestTemplates:
          application/json: "{\"statusCode\": 200}"
        type: "mock"
  '/contracts/{name}':
    get:
      tags:
      - Contract Service
      summary: Get contract
      description: Returns contract details for the given contract name
      security:
      - OAuth2:
        - 'read:contracts'
      x-amazon-apigateway-integration:
        passthroughBehavior: "when_no_match"
        requestTemplates:
          application/json: "{\"statusCode\": 200}"
        type: "mock"
  '/contracts/{name}/invoke':
    post:
      tags:
      - Contract Service
      summary: Invoke a contract
      description: Invoke a contract
      security:
      - OAuth2:
        - 'read:contracts'
        - 'execute:contracts'
      x-amazon-apigateway-integration:
        passthroughBehavior: "when_no_match"
        requestTemplates:
          application/json: "{\"statusCode\": 200}"
        type: "mock"
  /transactions/payments:
    post:
      tags:
      - Payment Service
      summary: 'Create a signed payment transaction to transfer ETH between 2 accounts'
      description: 'Transfers Ether between 2 accounts. The source account must have sufficient balance to pay the gas fee.'
      operationId: createPayment
      security:
      - OAuth2:
        - 'write:payments'
      x-amazon-apigateway-integration:
        passthroughBehavior: "when_no_match"
        requestTemplates:
          application/json: "{\"statusCode\": 200}"
        type: "mock"
  /transactions/tokenpayments:
    post:
      tags:
      - Payment Service
      summary: 'Create a signed payment transaction to transfer ERC-20 tokens between 2 accounts'
      description: 'Transfers ERC-20 tokens between 2 accounts. The source account must have sufficient balance to pay the gas fee.'
      operationId: createTokenPayment
      security:
      - OAuth2:
        - 'write:payments'
      x-amazon-apigateway-integration:
        passthroughBehavior: "when_no_match"
        requestTemplates:
          application/json: "{\"statusCode\": 200}"
        type: "mock"
